export const SHOW_LOGIN = 'showLogin'
export const SET_USER_NAME = 'setUsername'
export const SET_USER_PASSWORD = 'setUserPassword'
export const SET_USER_FULL_NAME = 'setUserFullname'
export const SET_USER_TOKEN = 'setUserToken'
export const ADD_ERROR = 'addError'
export const CLEAR_ERRORS = 'clearErrors'
